apiVersion: apps/v1
kind: Deployment
metadata:
  name: webin-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webin-portal
  template:
    metadata:
      labels:
        run: webin-portal
    spec:
      containers:
        - name: webin-portal
          image: %DOCKER_IMAGE%
          ports:
            - containerPort: 80
       #     - containerPort: 443
      imagePullSecrets:
        - name: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: webin-portal
  labels:
    run: webin-portal
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  #  - port: 443
  #    protocol: TCP
  #    name: https
  selector:
    run: webin-portal
