# not required at this moment - to be removed later if not at all useful
apiVersion: v1
kind: Service
metadata:
  name: webin-portal-lb-service
spec:
  selector:
    app: webin-portal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127
